-- BirdBrain historical import support
-- Preserve legacy facts even when old round-level source records no longer exist.

BEGIN;

-- Historical layouts may appear only in Aces/Course Records, where par is not
-- available in the current workbook. Future scheduled layouts should still
-- supply a real par through application validation.
ALTER TABLE layouts ALTER COLUMN par DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sham_pool_round_stats (
  sham_pool_round_stat_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES seasons(season_id) ON DELETE CASCADE,
  round_id bigint REFERENCES rounds(round_id) ON DELETE CASCADE,
  legacy_round_no integer NOT NULL CHECK (legacy_round_no > 0),
  course_name text NOT NULL,
  layout_name text NOT NULL,
  par integer,
  pool text NOT NULL CHECK (pool IN ('A','B','C','D','E')),
  players integer NOT NULL CHECK (players >= 0),
  strokes integer NOT NULL CHECK (strokes >= 0),
  average numeric,
  stddev numeric,
  par_strokes integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (season_id, legacy_round_no, pool)
);

-- Existing all-time aces can predate the current workbook. Allow a historical
-- ace to identify the player/layout/date directly without fabricating a round.
-- Legacy BirdBrain could split a multiple-ace pot fractionally, so preserve the
-- recorded amount exactly even though future rules require whole-dollar awards.
ALTER TABLE ace_awards
  ALTER COLUMN payout TYPE numeric(12,2) USING payout::numeric,
  ALTER COLUMN round_id DROP NOT NULL,
  ALTER COLUMN round_participant_id DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS player_id bigint REFERENCES players(player_id),
  ADD COLUMN IF NOT EXISTS layout_id bigint REFERENCES layouts(layout_id),
  ADD COLUMN IF NOT EXISTS achieved_on date;

DO $$
BEGIN
  ALTER TABLE ace_awards
    ADD CONSTRAINT ace_awards_has_identity
    CHECK (round_participant_id IS NOT NULL OR player_id IS NOT NULL);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS ux_historical_ace
  ON ace_awards(player_id, achieved_on, layout_id, hole_number)
  WHERE round_participant_id IS NULL;

-- Course-record history likewise may predate detailed round retention.
ALTER TABLE course_records ALTER COLUMN round_id DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_historical_course_record
  ON course_records(layout_id, player_id, achieved_on, score)
  WHERE round_id IS NULL;

DROP VIEW IF EXISTS v_aces;

CREATE VIEW v_aces AS
SELECT
  COALESCE(p.display_name, pp.display_name, rp.display_name) AS "Name",
  COALESCE(r.scheduled_date, aa.achieved_on) AS "Date",
  c.name AS "Course",
  l.name AS "Layout",
  aa.hole_number AS "Hole",
  aa.payout AS "Payout"
FROM ace_awards aa
LEFT JOIN round_participants rp
  ON rp.round_participant_id = aa.round_participant_id
LEFT JOIN players pp ON pp.player_id = rp.player_id
LEFT JOIN players p ON p.player_id = aa.player_id
LEFT JOIN rounds r ON r.round_id = aa.round_id
JOIN layouts l ON l.layout_id = COALESCE(aa.layout_id, r.layout_id)
JOIN courses c ON c.course_id = l.course_id;

COMMIT;
