-- BirdBrain read-only migration staging
-- Stores exact Google Sheet snapshots before normalized transformation.

BEGIN;

CREATE SCHEMA IF NOT EXISTS migration_staging;

CREATE TABLE IF NOT EXISTS migration_staging.snapshots (
  snapshot_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  spreadsheet_id text NOT NULL,
  source_url text NOT NULL,
  captured_at timestamptz NOT NULL,
  loaded_at timestamptz NOT NULL DEFAULT now(),
  manifest jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS migration_staging.snapshot_sheets (
  snapshot_id bigint NOT NULL
    REFERENCES migration_staging.snapshots(snapshot_id) ON DELETE CASCADE,
  sheet_name text NOT NULL,
  file_name text NOT NULL,
  row_count integer NOT NULL CHECK (row_count >= 0),
  headers jsonb NOT NULL,
  sha256 text NOT NULL,
  PRIMARY KEY (snapshot_id, sheet_name)
);

CREATE TABLE IF NOT EXISTS migration_staging.google_sheet_rows (
  snapshot_id bigint NOT NULL,
  sheet_name text NOT NULL,
  row_number integer NOT NULL CHECK (row_number > 0),
  row_data jsonb NOT NULL,
  PRIMARY KEY (snapshot_id, sheet_name, row_number),
  FOREIGN KEY (snapshot_id, sheet_name)
    REFERENCES migration_staging.snapshot_sheets(snapshot_id, sheet_name)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_staging_rows_sheet
  ON migration_staging.google_sheet_rows(snapshot_id, sheet_name);

COMMENT ON SCHEMA migration_staging IS
  'Read-only source snapshots used during BirdBrain migration; not application state.';

COMMIT;
