-- BirdBrain PostgreSQL migration v1
-- Target: managed PostgreSQL / Supabase development project
-- This schema is intentionally independent of the live Google Sheet.

BEGIN;

CREATE TABLE IF NOT EXISTS leagues (
  league_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  timezone text NOT NULL DEFAULT 'America/Chicago',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS seasons (
  season_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  league_id bigint NOT NULL REFERENCES leagues(league_id),
  season_name text NOT NULL,
  season_year integer,
  qualification_points integer NOT NULL DEFAULT 300 CHECK (qualification_points >= 0),
  postseason_started_at timestamptz,
  closed_at timestamptz,
  UNIQUE (league_id, season_name)
);

CREATE TABLE IF NOT EXISTS players (
  player_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name text NOT NULL,
  normalized_name text NOT NULL,
  phone text,
  auth_user_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  retired_at timestamptz,
  UNIQUE (normalized_name)
);

CREATE TABLE IF NOT EXISTS season_memberships (
  season_membership_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES seasons(season_id),
  player_id bigint NOT NULL REFERENCES players(player_id),
  is_tag_holder boolean NOT NULL DEFAULT true,
  public_phone_visible boolean NOT NULL DEFAULT false,
  captain_default boolean NOT NULL DEFAULT false,
  joined_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (season_id, player_id)
);

CREATE TABLE IF NOT EXISTS courses (
  course_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS layouts (
  layout_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id bigint NOT NULL REFERENCES courses(course_id),
  name text NOT NULL,
  par integer NOT NULL CHECK (par > 0),
  hole_count integer NOT NULL DEFAULT 18 CHECK (hole_count > 0),
  UNIQUE (course_id, name)
);

CREATE TABLE IF NOT EXISTS layout_holes (
  layout_id bigint NOT NULL REFERENCES layouts(layout_id) ON DELETE CASCADE,
  hole_number integer NOT NULL CHECK (hole_number > 0),
  par integer NOT NULL CHECK (par BETWEEN 2 AND 7),
  PRIMARY KEY (layout_id, hole_number)
);

CREATE TABLE IF NOT EXISTS rounds (
  round_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES seasons(season_id),
  round_no integer NOT NULL CHECK (round_no > 0),
  layout_id bigint NOT NULL REFERENCES layouts(layout_id),
  scheduled_date date NOT NULL,
  start_time time,
  note text,
  points_multiplier integer NOT NULL DEFAULT 1 CHECK (points_multiplier > 0),
  payout_contribution integer NOT NULL DEFAULT 4 CHECK (payout_contribution >= 0),
  postseason_contribution integer NOT NULL DEFAULT 1 CHECK (postseason_contribution >= 0),
  ace_contribution integer NOT NULL DEFAULT 1 CHECK (ace_contribution >= 0),
  status text NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','check_in','in_progress','results_review','finalized')),
  check_in_closed_at timestamptz,
  finalized_at timestamptz,
  results_published_at timestamptz,
  UNIQUE (season_id, round_no)
);

CREATE TABLE IF NOT EXISTS round_participants (
  round_participant_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  round_id bigint NOT NULL REFERENCES rounds(round_id) ON DELETE CASCADE,
  player_id bigint REFERENCES players(player_id),
  display_name text NOT NULL,
  participant_type text NOT NULL DEFAULT 'member' CHECK (participant_type IN ('member','guest')),
  checked_in_at timestamptz,
  checked_in_by bigint REFERENCES players(player_id),
  started_round boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','dnf','withdrawn','disqualified','removed')),
  volunteer_captain boolean NOT NULL DEFAULT false,
  UNIQUE (round_id, player_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_round_guest_name
  ON round_participants(round_id, lower(display_name))
  WHERE player_id IS NULL;

CREATE TABLE IF NOT EXISTS cards (
  card_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  round_id bigint NOT NULL REFERENCES rounds(round_id) ON DELETE CASCADE,
  card_no integer NOT NULL,
  starting_position text,
  captain_round_participant_id bigint REFERENCES round_participants(round_participant_id),
  published_at timestamptz,
  UNIQUE (round_id, card_no)
);

CREATE TABLE IF NOT EXISTS card_members (
  card_id bigint NOT NULL REFERENCES cards(card_id) ON DELETE CASCADE,
  round_participant_id bigint NOT NULL REFERENCES round_participants(round_participant_id) ON DELETE CASCADE,
  seat_no integer,
  PRIMARY KEY (card_id, round_participant_id),
  UNIQUE (round_participant_id)
);

CREATE TABLE IF NOT EXISTS hole_scores (
  hole_score_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  round_participant_id bigint NOT NULL REFERENCES round_participants(round_participant_id) ON DELETE CASCADE,
  hole_number integer NOT NULL CHECK (hole_number > 0),
  strokes integer NOT NULL CHECK (strokes > 0),
  source text NOT NULL DEFAULT 'udisc' CHECK (source IN ('udisc','birdbrain','admin')),
  entered_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (round_participant_id, hole_number)
);

CREATE TABLE IF NOT EXISTS round_results (
  round_result_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  round_participant_id bigint NOT NULL UNIQUE REFERENCES round_participants(round_participant_id) ON DELETE CASCADE,
  gross_score integer,
  score_to_par integer,
  applied_handicap numeric(10,4),
  net_score numeric(10,4),
  competition_rank integer,
  official_finish integer,
  cash_position integer,
  points integer NOT NULL DEFAULT 0 CHECK (points >= 0),
  payout_award integer NOT NULL DEFAULT 0 CHECK (payout_award >= 0),
  finalized_at timestamptz
);

CREATE TABLE IF NOT EXISTS playoff_resolutions (
  playoff_resolution_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  round_id bigint NOT NULL REFERENCES rounds(round_id) ON DELETE CASCADE,
  round_participant_id bigint NOT NULL REFERENCES round_participants(round_participant_id) ON DELETE CASCADE,
  resolved_finish integer NOT NULL CHECK (resolved_finish > 0),
  resolved_by bigint REFERENCES players(player_id),
  resolved_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (round_id, round_participant_id)
);

CREATE TABLE IF NOT EXISTS handicap_adjustments (
  handicap_adjustment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id bigint NOT NULL REFERENCES players(player_id),
  round_id bigint NOT NULL REFERENCES rounds(round_id),
  adjustment numeric(12,6) NOT NULL,
  method text NOT NULL CHECK (method IN ('pre_sham_par','sham')),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (player_id, round_id)
);

CREATE TABLE IF NOT EXISTS handicap_calculations (
  handicap_calculation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id bigint NOT NULL REFERENCES players(player_id),
  effective_after_round_id bigint NOT NULL REFERENCES rounds(round_id),
  precise_handicap numeric(12,6),
  applied_handicap integer,
  trim_fraction numeric(5,4) NOT NULL DEFAULT 0.20,
  calculated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (player_id, effective_after_round_id)
);

CREATE TABLE IF NOT EXISTS handicap_calculation_adjustments (
  handicap_calculation_id bigint NOT NULL REFERENCES handicap_calculations(handicap_calculation_id) ON DELETE CASCADE,
  handicap_adjustment_id bigint NOT NULL REFERENCES handicap_adjustments(handicap_adjustment_id),
  included boolean NOT NULL,
  trim_side text CHECK (trim_side IN ('low','high')),
  PRIMARY KEY (handicap_calculation_id, handicap_adjustment_id)
);

CREATE TABLE IF NOT EXISTS player_pool_assignments (
  player_pool_assignment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES seasons(season_id),
  player_id bigint NOT NULL REFERENCES players(player_id),
  pool text CHECK (pool IN ('A','B','C','D','E')),
  effective_round_no integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (season_id, player_id, effective_round_no)
);

CREATE TABLE IF NOT EXISTS sham_layout_models (
  sham_layout_model_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES seasons(season_id),
  layout_id bigint NOT NULL REFERENCES layouts(layout_id),
  effective_after_round_no integer NOT NULL,
  total_rounds integer,
  stroke_total numeric,
  par_total numeric,
  grand_mean numeric,
  rating numeric,
  slope numeric,
  standardized_slope numeric,
  weight numeric,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (season_id, layout_id, effective_after_round_no)
);

CREATE TABLE IF NOT EXISTS financial_transactions (
  financial_transaction_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  league_id bigint NOT NULL REFERENCES leagues(league_id),
  season_id bigint REFERENCES seasons(season_id),
  round_id bigint REFERENCES rounds(round_id),
  player_id bigint REFERENCES players(player_id),
  fund_type text NOT NULL CHECK (fund_type IN ('round_payout','ace_pot','postseason')),
  transaction_type text NOT NULL CHECK (transaction_type IN ('contribution','ace_pot_contribution','award','donation','season_contribution','adjustment','reversal')),
  amount integer NOT NULL CHECK (amount <> 0),
  reversal_of_transaction_id bigint REFERENCES financial_transactions(financial_transaction_id),
  memo text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES players(player_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_single_reversal
  ON financial_transactions(reversal_of_transaction_id)
  WHERE reversal_of_transaction_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS ace_awards (
  ace_award_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  round_id bigint NOT NULL REFERENCES rounds(round_id),
  round_participant_id bigint NOT NULL REFERENCES round_participants(round_participant_id),
  hole_number integer NOT NULL CHECK (hole_number > 0),
  payout integer NOT NULL CHECK (payout >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (round_participant_id, hole_number)
);

CREATE TABLE IF NOT EXISTS course_records (
  course_record_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  layout_id bigint NOT NULL REFERENCES layouts(layout_id),
  round_id bigint NOT NULL REFERENCES rounds(round_id),
  player_id bigint NOT NULL REFERENCES players(player_id),
  score integer NOT NULL,
  achieved_on date NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (layout_id, round_id, player_id)
);

CREATE TABLE IF NOT EXISTS hall_of_champions (
  champion_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES seasons(season_id),
  player_id bigint NOT NULL REFERENCES players(player_id),
  title text NOT NULL,
  awarded_on date,
  UNIQUE (season_id, player_id, title)
);

CREATE TABLE IF NOT EXISTS round_warning_acknowledgements (
  warning_acknowledgement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  round_id bigint NOT NULL REFERENCES rounds(round_id) ON DELETE CASCADE,
  warning_code text NOT NULL,
  warning_fingerprint text NOT NULL,
  acknowledged_by bigint REFERENCES players(player_id),
  acknowledged_at timestamptz NOT NULL DEFAULT now(),
  note text,
  UNIQUE (round_id, warning_fingerprint)
);

CREATE TABLE IF NOT EXISTS audit_events (
  audit_event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  league_id bigint NOT NULL REFERENCES leagues(league_id),
  season_id bigint REFERENCES seasons(season_id),
  round_id bigint REFERENCES rounds(round_id),
  actor_player_id bigint REFERENCES players(player_id),
  event_type text NOT NULL,
  event_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Compatibility views for the current Shiny UI.
CREATE OR REPLACE VIEW v_schedule AS
SELECT
  r.round_id,
  r.round_no AS "RoundNo",
  c.name AS "Course",
  l.name AS "Layout",
  r.scheduled_date AS "Datend",
  to_char(r.scheduled_date, 'Mon DD') AS "Date",
  r.start_time AS "StartTime",
  r.note AS "Note"
FROM rounds r
JOIN layouts l ON l.layout_id = r.layout_id
JOIN courses c ON c.course_id = l.course_id;

CREATE OR REPLACE VIEW v_leaderboard AS
SELECT
  p.player_id,
  p.display_name AS "Name",
  COALESCE(SUM(rr.points) FILTER (WHERE rp.participant_type = 'member'), 0)::integer AS "Points",
  COUNT(rr.round_result_id) FILTER (
    WHERE rp.participant_type = 'member'
      AND rp.status <> 'removed'
      AND r.status = 'finalized'
  )::integer AS "Rounds",
  CASE
    WHEN hc.applied_handicap IS NULL OR hc.applied_handicap = 0 THEN 'E'
    WHEN hc.applied_handicap > 0 THEN '+' || hc.applied_handicap::text
    ELSE hc.applied_handicap::text
  END AS "Handicap"
FROM season_memberships sm
JOIN players p ON p.player_id = sm.player_id
JOIN seasons s ON s.season_id = sm.season_id
LEFT JOIN round_participants rp ON rp.player_id = p.player_id
LEFT JOIN rounds r ON r.round_id = rp.round_id AND r.season_id = s.season_id
LEFT JOIN round_results rr ON rr.round_participant_id = rp.round_participant_id
LEFT JOIN LATERAL (
  SELECT h.applied_handicap
  FROM handicap_calculations h
  WHERE h.player_id = p.player_id
  ORDER BY h.calculated_at DESC, h.handicap_calculation_id DESC
  LIMIT 1
) hc ON true
WHERE s.closed_at IS NULL
GROUP BY p.player_id, p.display_name, hc.applied_handicap;

CREATE OR REPLACE VIEW v_current_all_time AS
SELECT
  p.display_name AS "Name",
  COUNT(DISTINCT sm.season_id)::integer AS "Seasons",
  COUNT(rr.round_result_id) FILTER (
    WHERE rp.participant_type = 'member' AND r.status = 'finalized'
  )::integer AS "Rounds",
  COALESCE(SUM(rr.points) FILTER (WHERE rp.participant_type = 'member'), 0)::integer AS "Points",
  (FLOOR(COALESCE(SUM(rr.points),0) / 500.0) * 500)::integer AS milestonen
FROM players p
LEFT JOIN season_memberships sm ON sm.player_id = p.player_id
LEFT JOIN round_participants rp ON rp.player_id = p.player_id
LEFT JOIN rounds r ON r.round_id = rp.round_id
LEFT JOIN round_results rr ON rr.round_participant_id = rp.round_participant_id
GROUP BY p.player_id, p.display_name;

CREATE OR REPLACE VIEW v_course_records AS
SELECT
  c.name AS "Course",
  l.name AS "Layout",
  p.display_name AS "Name",
  cr.score AS "Score",
  cr.achieved_on AS "Date"
FROM course_records cr
JOIN layouts l ON l.layout_id = cr.layout_id
JOIN courses c ON c.course_id = l.course_id
JOIN players p ON p.player_id = cr.player_id
WHERE cr.score = (
  SELECT MIN(cr2.score)
  FROM course_records cr2
  WHERE cr2.layout_id = cr.layout_id
);

CREATE OR REPLACE VIEW v_aces AS
SELECT
  p.display_name AS "Name",
  r.scheduled_date AS "Date",
  c.name AS "Course",
  l.name AS "Layout",
  aa.hole_number AS "Hole",
  aa.payout AS "Payout"
FROM ace_awards aa
JOIN round_participants rp ON rp.round_participant_id = aa.round_participant_id
LEFT JOIN players p ON p.player_id = rp.player_id
JOIN rounds r ON r.round_id = aa.round_id
JOIN layouts l ON l.layout_id = r.layout_id
JOIN courses c ON c.course_id = l.course_id;

CREATE OR REPLACE VIEW v_hall_of_champions AS
SELECT
  s.season_name AS "Season",
  p.display_name AS "Name",
  hc.title AS "Title",
  hc.awarded_on AS "Date"
FROM hall_of_champions hc
JOIN seasons s ON s.season_id = hc.season_id
JOIN players p ON p.player_id = hc.player_id;

CREATE INDEX IF NOT EXISTS ix_rounds_season_date ON rounds(season_id, scheduled_date);
CREATE INDEX IF NOT EXISTS ix_round_participants_round ON round_participants(round_id);
CREATE INDEX IF NOT EXISTS ix_round_participants_player ON round_participants(player_id);
CREATE INDEX IF NOT EXISTS ix_round_results_points ON round_results(points);
CREATE INDEX IF NOT EXISTS ix_financial_transactions_round ON financial_transactions(round_id);
CREATE INDEX IF NOT EXISTS ix_financial_transactions_player ON financial_transactions(player_id);
CREATE INDEX IF NOT EXISTS ix_handicap_adjustments_player ON handicap_adjustments(player_id);

COMMIT;
