-- BirdBrain compatibility corrections and aggregate-history support
-- Keeps legacy public Shiny outputs compatible while normalized facts become authoritative.

BEGIN;

ALTER TABLE rounds
  ADD COLUMN IF NOT EXISTS display_date text,
  ADD COLUMN IF NOT EXISTS display_start_time text,
  ADD COLUMN IF NOT EXISTS ace_pot_start integer;

DO $$
BEGIN
  ALTER TABLE rounds
    ADD CONSTRAINT rounds_ace_pot_start_nonnegative
    CHECK (ace_pot_start IS NULL OR ace_pot_start >= 0);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Older seasons may only exist as Name/Points/Rounds/Season aggregates in
-- the legacy workbook. The ongoing season also uses one baseline row per player
-- through the migration cutoff round. Future normalized round results are added
-- after that cutoff; this avoids fabricating historical playoff-point detail that
-- the Sheet no longer stores.
CREATE TABLE IF NOT EXISTS season_player_summaries (
  season_player_summary_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES seasons(season_id) ON DELETE CASCADE,
  player_id bigint NOT NULL REFERENCES players(player_id) ON DELETE CASCADE,
  rounds integer NOT NULL DEFAULT 0 CHECK (rounds >= 0),
  points integer NOT NULL DEFAULT 0 CHECK (points >= 0),
  through_round_no integer CHECK (through_round_no IS NULL OR through_round_no >= 0),
  source text NOT NULL DEFAULT 'legacy_sheet',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (season_id, player_id)
);

-- The legacy Hall of Champions sheet is Event / Year / Division / Name / Score.
-- Keep the original internal title fields, but add compatibility fields instead
-- of forcing historical data into a lossy shape.
ALTER TABLE hall_of_champions
  ADD COLUMN IF NOT EXISTS event_name text,
  ADD COLUMN IF NOT EXISTS event_year integer,
  ADD COLUMN IF NOT EXISTS division text,
  ADD COLUMN IF NOT EXISTS score_text text;

UPDATE hall_of_champions hc
SET
  event_name = COALESCE(hc.event_name, hc.title),
  event_year = COALESCE(
    hc.event_year,
    (SELECT s.season_year FROM seasons s WHERE s.season_id = hc.season_id)
  )
WHERE hc.event_name IS NULL OR hc.event_year IS NULL;

DROP VIEW IF EXISTS v_hall_of_champions;
DROP VIEW IF EXISTS v_aces;
DROP VIEW IF EXISTS v_course_records;
DROP VIEW IF EXISTS v_current_all_time;
DROP VIEW IF EXISTS v_leaderboard;
DROP VIEW IF EXISTS v_schedule;

CREATE VIEW v_schedule AS
SELECT
  r.round_id,
  c.name AS "Course",
  l.name AS "Layout",
  r.scheduled_date AS "Datend",
  COALESCE(r.display_date, to_char(r.scheduled_date, 'Mon DD')) AS "Date",
  COALESCE(
    r.display_start_time,
    CASE WHEN r.start_time IS NULL THEN NULL ELSE to_char(r.start_time, 'FMHH12:MI AM') END
  ) AS "StartTime",
  r.note AS "Note",
  r.round_no AS "RoundNo",
  r.ace_pot_start AS "AcePot",
  l.par AS "Par",
  (
    SELECT string_agg(lh.hole_number::text, ',' ORDER BY lh.hole_number)
    FROM layout_holes lh
    WHERE lh.layout_id = l.layout_id AND lh.par = 4
  ) AS "ParFours",
  (
    SELECT string_agg(lh.hole_number::text, ',' ORDER BY lh.hole_number)
    FROM layout_holes lh
    WHERE lh.layout_id = l.layout_id AND lh.par = 5
  ) AS "ParFives"
FROM rounds r
JOIN layouts l ON l.layout_id = r.layout_id
JOIN courses c ON c.course_id = l.course_id;

-- Current-season standings use a migration baseline when one exists, then add
-- only finalized normalized results after baseline.through_round_no.
CREATE VIEW v_leaderboard AS
SELECT
  p.player_id,
  p.display_name AS "Name",
  (
    COALESCE(sps.points, 0) +
    COALESCE(
      SUM(rr.points) FILTER (
        WHERE rp.participant_type = 'member'
          AND rp.status <> 'removed'
          AND r.status = 'finalized'
      ),
      0
    )
  )::integer AS "Points",
  (
    COALESCE(sps.rounds, 0) +
    COUNT(rr.round_result_id) FILTER (
      WHERE rp.participant_type = 'member'
        AND rp.status <> 'removed'
        AND r.status = 'finalized'
    )
  )::integer AS "Rounds",
  CASE
    WHEN hc.applied_handicap IS NULL OR hc.applied_handicap = 0 THEN 'E'
    WHEN hc.applied_handicap > 0 THEN '+' || hc.applied_handicap::text
    ELSE hc.applied_handicap::text
  END AS "Handicap"
FROM season_memberships sm
JOIN seasons s ON s.season_id = sm.season_id
JOIN players p ON p.player_id = sm.player_id
LEFT JOIN season_player_summaries sps
  ON sps.season_id = sm.season_id
 AND sps.player_id = sm.player_id
LEFT JOIN rounds r
  ON r.season_id = s.season_id
 AND (
      sps.season_player_summary_id IS NULL
      OR (
        sps.through_round_no IS NOT NULL
        AND r.round_no > sps.through_round_no
      )
 )
LEFT JOIN round_participants rp
  ON rp.round_id = r.round_id
 AND rp.player_id = p.player_id
LEFT JOIN round_results rr ON rr.round_participant_id = rp.round_participant_id
LEFT JOIN LATERAL (
  SELECT h.applied_handicap
  FROM handicap_calculations h
  JOIN rounds hr ON hr.round_id = h.effective_after_round_id
  WHERE h.player_id = p.player_id
    AND hr.season_id = s.season_id
  ORDER BY hr.round_no DESC, h.calculated_at DESC, h.handicap_calculation_id DESC
  LIMIT 1
) hc ON true
WHERE s.closed_at IS NULL
GROUP BY
  p.player_id,
  p.display_name,
  sps.season_player_summary_id,
  sps.points,
  sps.rounds,
  sps.through_round_no,
  hc.applied_handicap;

-- Build one row per player/season. A full historical summary (through_round_no
-- NULL) suppresses detailed results. A current migration baseline adds only
-- detailed results after its cutoff. With no summary, all finalized detail counts.
CREATE VIEW v_current_all_time AS
WITH season_rows AS (
  SELECT
    sm.season_id,
    sm.player_id,
    (
      COALESCE(sps.rounds, 0) +
      COUNT(rr.round_result_id) FILTER (
        WHERE rp.participant_type = 'member'
          AND rp.status <> 'removed'
          AND r.status = 'finalized'
      )
    )::integer AS rounds,
    (
      COALESCE(sps.points, 0) +
      COALESCE(
        SUM(rr.points) FILTER (
          WHERE rp.participant_type = 'member'
            AND rp.status <> 'removed'
            AND r.status = 'finalized'
        ),
        0
      )
    )::integer AS points
  FROM season_memberships sm
  LEFT JOIN season_player_summaries sps
    ON sps.season_id = sm.season_id
   AND sps.player_id = sm.player_id
  LEFT JOIN rounds r
    ON r.season_id = sm.season_id
   AND (
        sps.season_player_summary_id IS NULL
        OR (
          sps.through_round_no IS NOT NULL
          AND r.round_no > sps.through_round_no
        )
   )
  LEFT JOIN round_participants rp
    ON rp.round_id = r.round_id
   AND rp.player_id = sm.player_id
  LEFT JOIN round_results rr ON rr.round_participant_id = rp.round_participant_id
  GROUP BY
    sm.season_id,
    sm.player_id,
    sps.season_player_summary_id,
    sps.rounds,
    sps.points,
    sps.through_round_no
)
SELECT
  p.display_name AS "Name",
  COUNT(sr.season_id)::integer AS "Seasons",
  COALESCE(SUM(sr.rounds), 0)::integer AS "Rounds",
  COALESCE(SUM(sr.points), 0)::integer AS "Points",
  (FLOOR(COALESCE(SUM(sr.points), 0) / 500.0) * 500)::integer AS milestonen
FROM players p
LEFT JOIN season_rows sr ON sr.player_id = p.player_id
GROUP BY p.player_id, p.display_name;

CREATE VIEW v_course_records AS
SELECT
  c.name AS "Course",
  l.name AS "Layout",
  p.display_name AS "Name",
  cr.score AS "Score",
  cr.achieved_on AS "Date"
FROM course_records cr
JOIN layouts l ON l.layout_id = cr.layout_id
JOIN courses c ON c.course_id = l.course_id
JOIN players p ON p.player_id = cr.player_id
WHERE cr.score = (
  SELECT MIN(cr2.score)
  FROM course_records cr2
  WHERE cr2.layout_id = cr.layout_id
);

CREATE VIEW v_aces AS
SELECT
  COALESCE(p.display_name, rp.display_name) AS "Name",
  r.scheduled_date AS "Date",
  c.name AS "Course",
  l.name AS "Layout",
  aa.hole_number AS "Hole",
  aa.payout AS "Payout"
FROM ace_awards aa
JOIN round_participants rp ON rp.round_participant_id = aa.round_participant_id
LEFT JOIN players p ON p.player_id = rp.player_id
JOIN rounds r ON r.round_id = aa.round_id
JOIN layouts l ON l.layout_id = r.layout_id
JOIN courses c ON c.course_id = l.course_id;

CREATE VIEW v_hall_of_champions AS
SELECT
  COALESCE(hc.event_name, hc.title) AS "Event",
  COALESCE(hc.event_year, s.season_year) AS "Year",
  hc.division AS "Division",
  p.display_name AS "Name",
  hc.score_text AS "Score"
FROM hall_of_champions hc
JOIN seasons s ON s.season_id = hc.season_id
JOIN players p ON p.player_id = hc.player_id;

CREATE INDEX IF NOT EXISTS ix_season_player_summaries_player
  ON season_player_summaries(player_id);

COMMIT;
